# Generated by Django 3.2.4 on 2021-06-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('myfittempoapi', '0001_initial'), ('myfittempoapi', '0002_auto_20210620_0039'), ('myfittempoapi', '0003_auto_20210620_0045'), ('myfittempoapi', '0004_auto_20210620_1237'), ('myfittempoapi', '0005_auto_20210620_1249'), ('myfittempoapi', '0006_auto_20210620_2024'), ('myfittempoapi', '0007_auto_20210621_1813'), ('myfittempoapi', '0008_remove_carrito_cliente')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                
                ('primerNombre', models.CharField(default=0, max_length=50)),
                ('segundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('profesión', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fotoPerfil', models.CharField(blank=True, max_length=100, null=True)),
                ('fotoBanner', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaModificado', models.DateField(blank=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                
                ('primerNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaModificado', models.DateField(blank=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                
                ('fechaOferta', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('costo', models.FloatField()),
                ('estadoOferta', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaModificado', models.DateField(blank=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfittempoapi.empleado')),
            ],
            options={
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                
                ('estadoCarrito', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaModificado', models.DateField(blank=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ofertas', models.ManyToManyField(to='myfittempoapi.Oferta')),
            ],
            options={
                'verbose_name_plural': 'Carritos',
            },
        ),
    ]
