# Generated by Django 3.2.4 on 2021-06-26 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0002_alter_cliente_fechamodificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 25, 22, 14, 38, 153346)),
        ),
    ]
