# Generated by Django 3.2.4 on 2021-07-12 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0002_auto_20210711_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='primerNombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='segundoNombre',
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 48, 59, 967130)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 48, 59, 965128)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 48, 59, 965629)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 48, 59, 966629)),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 48, 59, 962627)),
        ),
    ]
