# Generated by Django 3.2.5 on 2021-07-17 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0003_auto_20210711_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 15, 16, 12, 128914)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 15, 16, 12, 126913)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 15, 16, 12, 127413)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 15, 16, 12, 128414)),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 15, 16, 12, 124911)),
        ),
    ]
