# Generated by Django 3.2.4 on 2021-06-26 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0003_cliente_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfittempoapi.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 12, 5, 17, 588347)),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 12, 5, 17, 586846)),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 12, 5, 17, 587346)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 12, 5, 17, 586346)),
        ),
    ]
