# Generated by Django 3.2.4 on 2021-06-26 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0004_auto_20210626_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 13, 17, 58, 454992)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 13, 17, 58, 452490)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 13, 17, 58, 453490)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fotoBanner',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fotoPerfil',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 13, 17, 58, 453991)),
        ),
    ]
