# Generated by Django 3.2.4 on 2021-07-05 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0010_auto_20210702_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='profesión',
            new_name='profesion',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 15, 56, 24109)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 15, 56, 22108)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 15, 56, 22608)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 15, 56, 23609)),
        ),
    ]
