# Generated by Django 3.2.4 on 2021-07-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfittempoapi', '0011_auto_20210705_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='init_point',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 14, 22, 47, 287846)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 14, 22, 47, 284843)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 14, 22, 47, 285844)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 14, 22, 47, 286845)),
        ),
    ]
